# Site settings
title: GISGeek - Awsome GIS resources and ideas
author:
  name: Christian Leidersdorff
description: "GISGeek website."

# Build settings
remote_theme: jekyll/minima

exclude: ["readme.md"]
